language: php

dist: jammy
addons:
  apt:
    packages:
      - "libonig5"

php:
  - 8.1
  - 8.2

sudo: false

env:
  matrix:
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 8.2
      env: PHPCS=1 DEFAULT=0

    - php: 8.2
      env: COVERAGE=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - if [[ $PHPCS == 1 ]]; then composer require --dev cakephp/cakephp-codesniffer:^5.0 ; fi

script:
  - if [[ $COVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml || true ; fi
  - if [[ $COVERAGE == 1 ]]; then curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -v ; fi

  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit --stderr ; fi

  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=vendor --ignore=tests/bootstrap.php . ; fi

notifications:
  email: false
